<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AMN.RetailOS.Application\AMN.RetailOS.Application.csproj" />
    <ProjectReference Include="..\AMN.RetailOS.Infrastructure\AMN.RetailOS.Infrastructure.csproj" />
  </ItemGroup>
</Project>
